loreal/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Start frontend routes

Route::group([
    'prefix'    => "admin",
    'namespace' => "Backend",
], function () {

    //loreal Sio Reports
    Route::group(['prefix' => "io-reports", 'as' => 'io_reports.'], function () {

        Route::get('/{id}/destroy', 'IoReportsController@destroy')->name('destroy');

        Route::get('/', 'IoReportsController@index')->name('index');

        Route::get('ajax/{id}/show', 'IoReportsController@ajax_show');

    });

    //loreal Incident Reports
    Route::group(['prefix' => "incident-reports", 'as' => 'incident_reports.'], function () {

        Route::get('/{id}/destroy', 'IncidentReportsController@destroy')->name('destroy');

        Route::get('/', 'IncidentReportsController@index')->name('index');

        Route::get('ajax/{id}/show', 'IncidentReportsController@ajax_show');

    });

//loreal Mesur Reports
    Route::group(['prefix' => "mesur-reports", 'as' => 'mesur_reports.'], function () {

        Route::get('/{id}/destroy', 'MesurReportsController@destroy')->name('destroy');

        Route::get('/', 'MesurReportsController@index')->name('index');

        Route::get('ajax/{id}/show', 'MesurReportsController@ajax_show');

    });




});

// Start frontend routes
Route::get('/', "HomeController@index")->name("frontend.home");
Route::group(['prefix' => 'frontend', 'as' => 'frontend.'], function () {
    Route::group(['prefix' => 'ajax', 'as' => 'ajax.'], function () {
        Route::post("employee/validate-id", "AjaxHomeController@validateEmpId")->name('validateEmpId');
        Route::get("area/locations", "AjaxHomeController@getAreaLocations")->name('get-area-locations');
        Route::get("risks/{type}", "AjaxHomeController@getRisksByType")->name('get-risks-by-type');

    });

    Route::group(['prefix' => 'reports', 'as' => 'reports.'], function () {
        Route::post("io/store", "ReportsController@storeIo")->name('io.store');
        Route::post("mesur/store", "ReportsController@storeMesur")->name('mesur.store');
        Route::post("incident/store", "ReportsController@storeIncident")->name('incident.store');
    });

});


Route::group(['prefix' => 'admin'], function () {
    Voyager::routes();
});

loreal/app/IncidentReport.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class IncidentReport extends Model
{

    protected $table = 'incident_reports';
    protected $fillable = ['id', 'type_loreal_site', 'reporter_id', 'injured_person_name',
                           'incident_date', 'time_between', 'incident_nature', 'incident_place', 'incident_type',
                           'injured_person_type', 'injured_person_position', 'lost_days', 'duty_days', 'circumstances',
                           'consequences', 'lesions_nature', 'lesions_location', 'causes_analysis', 'description_causes',
                           'actions_plans'];

    public function reporter()
    {
        return $this->belongsTo(Employee::class, 'reporter_id');
    }

}

loreal/app/Http/Controllers/Backend/IncidentReportsController.php
<?php

namespace App\Http\Controllers\Backend;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\User;
use App\IncidentReport;
use Validator;
use TCG\Voyager\Facades\Voyager;


class IncidentReportsController extends Controller
{
      public function index(){

         $data = IncidentReport::all();
        
         return view('loreal.backend.incident_reports.index')->with(compact('data'));
    } 

      public function ajax_show(Request $request, $id){

         $data = IncidentReport::find($id);
          if(!$data){
            return response()->json(['success' => false]);
          }

         $view = view('loreal.backend.incident_reports.ajax_show_report')->with(compact('data'))->render();

          return response()->json(['success' => true, 'view' =>  $view]);
    } 

    
    public function destroy(Request $request, $id){

      $report = IncidentReport::find($id);
      if(!$report){
        dd(1);
       return redirect()->back()->with([
                'message'    => 'Not Found Report !',
                'alert-type' => 'error',
            ]);
      }
       $report->delete();

       return redirect()->back()->with([
                'message'    => 'Delete Report Successfully !',
                'alert-type' => 'success',
            ]);



    }
}

loreal/app/Http/Controllers/Backend/IoReportsController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\IoReport;
use Illuminate\Http\Request;
use Validator;

class IoReportsController extends Controller
{
    public function index()
    {

        $data = IoReport::all();

        return view('loreal.backend.io_reports.index')->with(compact('data'));
    }

    public function ajax_show(Request $request, $id)
    {

        $data = IoReport::find($id);
        if (!$data) {
            return response()->json(['success' => false]);
        }

        $view = view('loreal.backend.io_reports.ajax_show_report')->with(compact('data', 'options'))->render();

        return response()->json(['success' => true, 'view' => $view]);
    }


    public function destroy(Request $request, $id)
    {

        $report = IoReport::find($id);
        if (!$report) {


            return redirect()->back()->with([
                'message'    => 'Not Found Report !',
                'alert-type' => 'error',
            ]);
        }
        $report->delete();

        return redirect()->back()->with([
            'message'    => 'Delete Report Successfully !',
            'alert-type' => 'success',
        ]);


    }
}

loreal/app/Http/Controllers/Backend/LorealSettingsController.php
<?php

namespace App\Http\Controllers\Backend;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\User;
use App\LorealSettings;
use Validator;

class LorealSettingsController extends Controller
{
      public function index(){

         $data = LorealSettings::all();
        
         return view('loreal.backend.settings.index')->with(compact('data'));
    } 

      public function ajax_get_options(Request $request, $id, $key = null){

         $data = LorealSettings::find($id);
          if(!$data){
            return response()->json(['success' => false]);
          }
          if(!$data->value){
            $options = [];
          }else{
            $options = json_decode($data->value);
          }

         $view = view('loreal.backend.settings.partials.options')->with(compact('data', 'options'))->render();

          return response()->json(['success' => true, 'view' =>  $view]);
    } 

      public function store_options(Request $request, $id, $key = null){

         $setting = LorealSettings::find($id);
         if(!$setting){
          return redirect()->back()->with('Not found that settings');
         }

         $storedOptions = [];

         $options = $request->get('options', []);
           
            foreach ($options as $option) {
          $storedOptions[$option['key']] = $option['value'];
            }
        $object = (object)$storedOptions;
        $setting->update(['value'=> json_encode($object)]);

       return redirect()->back()->with([
                'message'    => 'Updated Successfully !',
                'alert-type' => 'success',
            ]);
    } 
}

loreal/app/Http/Controllers/Backend/MesurReportsController.php
<?php

namespace App\Http\Controllers\Backend;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\User;
use App\MesurReport;
use Validator;

class MesurReportsController extends Controller
{
      public function index(){

         $data = MesurReport::all();
        
         return view('loreal.backend.mesur_reports.index')->with(compact('data'));
    } 

      public function ajax_show(Request $request, $id){

         $data = MesurReport::find($id);
          if(!$data){
            return response()->json(['success' => false]);
          }

         $view = view('loreal.backend.mesur_reports.ajax_show_report')->with(compact('data'))->render();

          return response()->json(['success' => true, 'view' =>  $view]);
    } 

    
    public function destroy(Request $request, $id){

      $report = MesurReport::find($id);
      if(!$report){
        dd(1);
       return redirect()->back()->with([
                'message'    => 'Not Found Report !',
                'alert-type' => 'error',
            ]);
      }
       $report->delete();

       return redirect()->back()->with([
                'message'    => 'Delete Report Successfully !',
                'alert-type' => 'success',
            ]);



    }
}

loreal/resources/views/loreal/backend/incident_reports/ajax_show_report.blade.php
<div id="ReportView">
    <style>

        .wrap-content {
            background: #fff;
            border: 1px solid #ddd;
            padding: 15px 30px;
        }

        .p0 {
            padding: 0;
        }

        .bg-e {
            background: #eee;
        }

        .bg-d {
            background: #ddd;
        }

        .bg-f9 {
            background: #f9f96ad9
        }

        .bg-f0 {
            background: #f0ffff;
        }

        .font-bold {
            font-weight: 700;
        }

        /**/

        table {
            border: 1px solid #333;
            border-top: 1px solid #333;
        }

        .table td, .table th {
            border-top: initial;
        }

        tr {
            height: 33px;
            max-height: auto
        }

        td {
            border-right: 1px solid #333;
            border-left: 1px solid #333;
            border-bottom: 1px solid #777;
        }

        /**/
        .table thead th {
            border: 1px solid #333;
            border-bottom: 1px solid #333;
        }

    </style>
    <style media="print">
        #printBtn {
            display: none;
        }
    </style>
    <div class="wrapper">
        <a href="#" id="printBtn" class="pull-right btn btn-primary hidden-print"
                            onclick="printContent('ReportView')"><i class="glyphicon glyphicon-print"></i> Print</a>

        <div class="wrap-content container">

            <header>
                <div class="row">
                    <div class="col-sm-12 text-center p-3 ">
                        <h3>REPORTING INFORMATION OF AN INCIDENT</h3>
                    </div>
                </div>
            </header>

            <br>

            <section>
                <table class="table table-sm text-center">
                    <thead>
                    <tr>
                        <th> Types of LOREAL Sites</th>
                        <th>Name of LOREAL Site(*) <br>
                            <small class="text-mute"><i>Name UsedFor Safty Reports</i></small>
                        </th>
                        <th> Name Of Person Reporting The incident</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td class="bg-f9">{{$data->type_loreal_site}}</td>
                        <td>{{$data->name_loreal_site}}</td>
                        <td>{{$data->incident_reporter_name}}</td>
                    </tr>

                    </tbody>
                </table>
            </section>

            <br>

            <section>
                <table class="table table-sm text-center">
                    <thead>
                    <tr>
                        <th>Date of the incident</th>
                        <th>Nature of the incident</th>
                        <th> Place of the incident</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td class="bg-f0">{{$data->incident_date}}</td>
                        <td class="bg-f0">{{$data->incident_nature}}</td>
                        <td class="bg-f0">{{$data->incident_place}}</td>
                    </tr>

                    </tbody>
                </table>
            </section>
            <br>
            <section>
                <table class="table table-sm text-center">
                    <thead>
                    <tr>
                        <th>Type of the accident</th>
                        <th>Injured person</th>
                        <th>Position</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td class="bg-f0">{{$data->incident_type}}</td>
                        <td class="bg-f0">{{$data->injured_person_type}}</td>
                        <td class="bg-f0">{{$data->injured_person_position}}</td>
                    </tr>

                    </tbody>
                </table>
            </section>
            <br>
            <section>
                <table class="table table-sm text-center">
                    <thead>
                    <tr>
                        <th>Number of days lost</th>
                        <th>Number of days in light duty</th>

                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td class="bg-f0">{{$data->lost_days}}</td>
                        <td class="bg-f0">{{$data->duty_days}}</td>

                    </tr>

                    </tbody>
                </table>
            </section>
            <br>


            <br>
            <section>
                <div class="row">
                    <div class="col-md-12 offset-md-2">
                        <table class="table table-sm text-center ">
                            <thead>
                            <tr>
                                <th> Circumstances - Sequence of events (join photos in the thumbnail "photo")</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr class="bg-f0" style="height: 100px;">
                                <td>{{$data->circumstances}}</td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </section>
            <br>

            <section>
                <div class="row">
                    <div class="col-md-12 offset-md-2">
                        <table class="table table-sm text-center ">
                            <thead>
                            <tr>
                                <th>Consequences (human, material, environmental …)</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr class="bg-f0" style="height: 100px;">
                                <td>{{$data->consequences}}</td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </section>
            <br>
            <section>
                <table class="table table-sm text-center">
                    <thead>
                    <tr>
                        <th>Nature of lesions</th>
                        <th>Location of lesions</th>

                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td class="bg-f0">{{$data->lesions_nature}}</td>
                        <td class="bg-f0">{{$data->lesions_location}}</td>

                    </tr>

                    </tbody>
                </table>
            </section>
            <br>

            <section>
                <table class="table table-sm text-center">
                    <thead>
                    <tr>
                        <th>Nature of lesions</th>
                        <th>Location of lesions</th>
                        <th>Root causes analysis</th>


                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td class="bg-f0">{{$data->lesions_nature}}</td>
                        <td class="bg-f0">{{$data->lesions_location}}</td>
                        <td class="bg-f0">{{$data->causes_analysis}}</td>

                    </tr>

                    </tbody>
                </table>
            </section>
            <br>

            <section>
                <div class="row">
                    <div class="col-md-12">
                        <table class="table table-sm text-center ">
                            <thead>
                            <tr>
                                <th>Possible causes</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr class="bg-f9" style="height: 100px;">
                                <td>{{$data->description_causes}}</td>
                            </tr>

                            </tbody>
                        </table>
                    </div>
                </div>

            </section>
            <br>
            <section>
                <div class="row">
                    <div class="col-md-12">
                        <table class="table table-sm text-center ">
                            <thead>
                            <tr>
                                <th>Plan of immediate actions / long-term</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr class="bg-f9" style="height: 100px;">
                                <td>{{$data->actions_plans}}</td>
                            </tr>

                            </tbody>
                        </table>
                    </div>
                </div>

            </section>
            <br>
            <section>
                <div class="row">
                    <div class="col-md-12">
                        <table class="table table-sm text-center ">
                            <thead>
                            <tr>
                                <th>Name, position, phone number and e.mail of the person to contact for more
                                    information
                                </th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr class="bg-f9" style="height: 100px;">
                                <td>{{$data->injured_person_name}}</td>
                            </tr>

                            </tbody>
                        </table>
                    </div>
                </div>

            </section>


        </div>
    </div>
</div>

<script>
    function printContent(id) {

        var divToPrint = document.getElementById(id);

        var newWin = window.open('', 'Print-Window');

        newWin.document.open();

        newWin.document.write('<html><body onload="window.print()">' + divToPrint.innerHTML + '</body></html>');

        newWin.document.close();

        setTimeout(function () {
            newWin.close();
        }, 10);

    }
</script>

loreal/resources/views/loreal/backend/incident_reports/index.blade.php
@extends('voyager::master')

@section('page_title', "Loreal Options")

@section('page_header')
    <div class="container-fluid">
        <h1 class="page-title">
            <i class="voyager-file-text"></i> Sio Reports 
        </h1>

    </div>
@stop
@section('content')
    <div class="page-content browse container-fluid">
        @include('voyager::alerts')
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-bordered">
                    <div class="panel-body">
                        <div class="table-responsive">
                            <table id="dataTable" class="table-responsive table table-hover">
                                <thead>
                                    <tr>
                                      <th>N</th>
                                      <th>Type of Loreal Site</th>
                                      <th>Name of Loreal Site</th>
                                      <th>Person reporting the incident</th>
                                      
                                      <th>injured Person</th>
                                      <th>Date of the incident</th>
                                      <th>Between</th>
                                     
                                      <th>Created at</th>
                                      <th>Actions</th>
                                    </tr>
                                    
                                </thead>
                                <tbody>
                              @foreach($data as $row) 
                                @php
                                $work_area_arr = json_decode($row->main_work_area, true);


                                @endphp
                                   <tr>
                                      <td>{{$loop->index + 1}}</td>
                                      <td>{{$row->type_loreal_site}}</td>
                                      <td>{{$row->name_loreal_site}}</td>
                                      <td>{{$row->incident_reporter_name}}</td>
                                      <td>{{$row->injured_person_name}}</td>
                                      <td>{{$row->incident_date}}</td>
                                      <td>{{$row->time_between}}</td>
                                     
                                      <td><code>{{\Carbon\Carbon::createFromTimeStamp(strtotime($row->created_at))->diffForHumans()}}</code></td>
                                      
                                      <td><a href="javascript:;" class="btn btn-primary" onclick="openIncidentReportModal('{{$row->id}}')">Show</a> <a href="{{route('incident_reports.destroy', $row->id)}}" class="btn btn-danger">Delete</a></td>
                                    </tr>
                               @endforeach     
                                </tbody>
                            </table>
                        </div>
                        
                    </div>
                </div>
            </div>
        </div>
    </div>

@include('loreal.backend.settings.partials.modal')
@stop

@section('css')

@stop

@section('javascript')
    <script>
        $(document).ready(function () {
          
         $('#dataTable').DataTable();
           
        });
    </script>

    <script>
        function openIncidentReportModal(id, key = null){
            $.ajax({
                 method: 'GET',
                 url:'/admin/incident-reports/ajax/'+id+'/show'
                }).done(function (data) {
                 $("#showReportsModal").modal({show: true}).find(".modal-body").html(data.view); 

                }).fail(function () {
                    alert('Somthing Happenned !');
                });
        }

    </script>
@stop

loreal/resources/views/loreal/backend/incident_reports/show.blade.php
@extends('voyager::master')

@section('page_title', "")

@section('page_header')
    <div class="container-fluid">
        <h1 class="page-title">
            <i class=""></i> 
        </h1>

    </div>
@stop

@section('content')
    <div class="page-content browse container-fluid">
        @include('voyager::alerts')
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-bordered">
                    <div class="panel-body">
                        <div class="table-responsive">
                            <table id="dataTable" class="table table-hover">
                                <thead>
                                    <tr>
                                      <th>hi</th>
                                      <th>ho</th>
                                      <th>po</th>
                                    </tr>
                                    
                                </thead>
                                <tbody>
                                   <tr>
                                      <td>vo</td>
                                      <td>jo</td>
                                      <td>do</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                        
                    </div>
                </div>
            </div>
        </div>
    </div>

 
@stop

@section('css')

@stop

@section('javascript')
    <script>
        $(document).ready(function () {
          
         $('#dataTable').DataTable();
           
        });
    </script>
@stop